#!/usr/bin/env python3
"""Generate OpenVM v2 host-check init files from each guest's openvm.toml.

`cargo openvm build` writes this small Rust include before compiling the real
guest target. The file is intentionally gitignored, but ordinary host
`cargo check`/`clippy` still expands `openvm::init!` and therefore needs it.
This generator keeps the fast host-check lane reproducible from a clean clone
without installing the heavyweight OpenVM CLI/nightly toolchain.

It mirrors the OpenVM v2.0.0 output shape used by Sybil's modular and short-
Weierstrass ECC extensions. Real guest builds and commitment reproduction stay
owned by `cargo openvm` / `just zk-rebuild-check`.
"""

from __future__ import annotations

import json
import re
import sys
import tomllib
from pathlib import Path


HEADER = "// This file is automatically generated by cargo openvm. Do not rename or edit."
IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
DECIMAL = re.compile(r"^[0-9]+$")


def generate(guest_dir: Path) -> None:
    config_path = guest_dir / "openvm.toml"
    with config_path.open("rb") as handle:
        config = tomllib.load(handle)

    app_vm = config.get("app_vm_config")
    if not isinstance(app_vm, dict):
        raise ValueError(f"{config_path}: missing [app_vm_config]")

    modular = app_vm.get("modular")
    moduli = modular.get("supported_moduli") if isinstance(modular, dict) else None
    if not isinstance(moduli, list) or not moduli:
        raise ValueError(f"{config_path}: modular.supported_moduli must be non-empty")
    if not all(isinstance(value, str) and DECIMAL.fullmatch(value) for value in moduli):
        raise ValueError(f"{config_path}: every supported modulus must be a decimal string")

    ecc = app_vm.get("ecc")
    curves = ecc.get("supported_curves") if isinstance(ecc, dict) else None
    if not isinstance(curves, list) or not curves:
        raise ValueError(f"{config_path}: ecc.supported_curves must be non-empty")
    names: list[str] = []
    for curve in curves:
        name = curve.get("struct_name") if isinstance(curve, dict) else None
        if not isinstance(name, str) or IDENTIFIER.fullmatch(name) is None:
            raise ValueError(f"{config_path}: invalid ECC struct_name {name!r}")
        names.append(name)

    quoted_moduli = ", ".join(json.dumps(value) for value in moduli)
    quoted_names = ", ".join(json.dumps(value) for value in names)
    generated = "\n".join(
        (
            HEADER,
            f"openvm_algebra_guest::moduli_macros::moduli_init! {{ {quoted_moduli} }}",
            f"openvm_ecc_guest::sw_macros::sw_init! {{ {quoted_names} }}",
            "",
        )
    )
    (guest_dir / "openvm_init.rs").write_text(generated, encoding="utf-8")
    print(f"generated {guest_dir / 'openvm_init.rs'}")


def main() -> int:
    if len(sys.argv) < 2:
        print(f"usage: {Path(sys.argv[0]).name} GUEST_DIR [GUEST_DIR ...]", file=sys.stderr)
        return 2
    try:
        for raw in sys.argv[1:]:
            generate(Path(raw))
    except (OSError, ValueError, tomllib.TOMLDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
