use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use matching_engine::{
    ConditionDir, Fill, MarketGroup, MarketId, MmConstraint, MmId, MmSide, Nanos, Order,
    OrderDirection, PriceCondition, Qty,
};
use serde::Serialize;
use sha2::{Digest as _, Sha256};
use sha3::Keccak256;
use sybil_l1_protocol::{
    append_deposit_frontier, deposit_leaf, deposit_prefix_roots, deposit_tree_leaf,
    empty_deposit_frontier, empty_deposit_root, DepositLeaf,
};
use sybil_verifier::commitments::{event_schema, hash_header, state_schema, witness_schema};
use sybil_verifier::{
    account_keys_digest, empty_account_keys_digest, AccountKeyDigestRecord,
    AccountReservationSnapshot, AccountSnapshot, BlockWitness, BridgeStateSnapshot,
    ChallengeSnapshot, DepositAccumulatorWitness, KeyOpAuth, KeyRecord, L1DepositWitness,
    MarketGroupSnapshot, MarketSnapshot, MarketStatusSnapshot, OracleSourceSnapshot,
    RejectionReason, ResolutionProposalSnapshot, ResolutionRecordSnapshot, RestingOrderSnapshot,
    StateSidecarSnapshot, SystemEventWitness, WithdrawalSnapshot, WitnessBlockHeader, WitnessOrder,
    WitnessRejection,
};
use sybil_zk::{state_transition_public_input_hash, witness_root, StateTransitionPublicInputs};

const COMMENT: &str = "Canonical cross-language vectors generated from the Rust encoders. This repo-root placement is the single file readable by both Cargo tests and Foundry tests. Regenerate with `just golden-write`; CI and `just golden-check` compare regenerated bytes exactly.";

#[derive(Serialize)]
struct GoldenVectors {
    _comment: &'static str,
    schema_version: u32,
    header: HeaderVector,
    state: StateVector,
    canonical_witness: WitnessVector,
    account_keys: AccountKeysVector,
    key_op_block: KeyOpBlockVector,
    quarantine_claim_block: QuarantineClaimBlockVector,
    deposits: DepositVectors,
    state_transition_public_inputs: PublicInputVector,
    escape_claim_public_inputs: EscapeClaimPublicInputVector,
}

#[derive(Serialize)]
struct HeaderVector {
    fixture: HeaderFixture,
    hash: String,
}

#[derive(Serialize)]
struct HeaderFixture {
    height: u64,
    parent_hash: String,
    state_root: String,
    events_root: String,
    order_count: u32,
    fill_count: u32,
    timestamp_ms: u64,
}

#[derive(Serialize)]
struct StateVector {
    leaf_count: usize,
    framed_sha256: String,
    leaves: Vec<StateLeafVector>,
}

#[derive(Serialize)]
struct StateLeafVector {
    key: String,
    value: String,
}

#[derive(Serialize)]
struct WitnessVector {
    length: usize,
    length_prefixed_sha256: String,
    bytes: String,
}

#[derive(Serialize)]
struct AccountKeysVector {
    account_id: u64,
    raw_p256_key: String,
    webauthn_key: String,
    empty_digest: String,
    two_keys_digest: String,
}

#[derive(Serialize)]
struct KeyOpBlockVector {
    registered_event_leaf: String,
    revoked_event_leaf: String,
    register_events_digest_bytes: String,
    revoke_events_digest_bytes: String,
    canonical_witness_length: usize,
    canonical_witness_sha256: String,
    events_root: String,
    witness_root: String,
}

#[derive(Serialize)]
struct QuarantineClaimBlockVector {
    quarantined_event_leaf: String,
    claimed_event_leaf: String,
    canonical_witness_length: usize,
    canonical_witness_sha256: String,
    events_root: String,
    witness_root: String,
}

#[derive(Serialize)]
struct DepositVectors {
    chain_id: u64,
    vault_address: String,
    token_address: String,
    empty_root: String,
    entries: Vec<DepositVector>,
    frontier_after_two_level_1: String,
    high_id_max_amount: HighDepositVector,
}

#[derive(Serialize)]
struct DepositVector {
    deposit_id: u64,
    sender: String,
    sybil_account_key: String,
    amount_token_units: u64,
    leaf: String,
    tree_leaf: String,
    prefix_root: String,
}

#[derive(Serialize)]
struct HighDepositVector {
    deposit_id: u64,
    sender: String,
    sybil_account_key: String,
    amount_token_units: u64,
    leaf: String,
    tree_leaf: String,
}

#[derive(Serialize)]
struct PublicInputVector {
    previous_height: u64,
    new_height: u64,
    previous_state_root: String,
    new_state_root: String,
    block_hash: String,
    events_root: String,
    witness_root: String,
    da_commitment: String,
    deposit_root: String,
    deposit_count: u64,
    hash: String,
}

#[derive(Serialize)]
struct EscapeClaimPublicInputVector {
    state_root: String,
    height: u64,
    account_id: u64,
    recipient: String,
    amount: u64,
    nullifier: String,
    hash: String,
}

struct EscapeClaimPublicInputs {
    state_root: [u8; 32],
    height: u64,
    account_id: u64,
    recipient: [u8; 20],
    amount: u64,
    nullifier: [u8; 32],
}

fn main() {
    if let Err(error) = run() {
        eprintln!("emit-golden: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let mode = std::env::args().nth(1);
    if std::env::args().nth(2).is_some() || !matches!(mode.as_deref(), Some("--write" | "--check"))
    {
        return Err("usage: emit-golden (--write|--check)".to_string());
    }

    let output = render()?;
    let path = output_path();
    match mode.as_deref() {
        Some("--write") => {
            let parent = path
                .parent()
                .ok_or_else(|| format!("output path has no parent: {}", path.display()))?;
            fs::create_dir_all(parent)
                .map_err(|error| format!("create {}: {error}", parent.display()))?;
            fs::write(&path, output.as_bytes())
                .map_err(|error| format!("write {}: {error}", path.display()))?;
            println!("wrote {}", path.display());
            Ok(())
        }
        Some("--check") => check_committed(&path, &output),
        _ => unreachable!("validated mode"),
    }
}

fn output_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("golden/golden-vectors.json")
}

fn check_committed(path: &Path, regenerated: &str) -> Result<(), String> {
    let committed = fs::read_to_string(path)
        .map_err(|error| format!("read {}: {error}; run `just golden-write`", path.display()))?;
    if committed == regenerated {
        println!("golden vectors match {}", path.display());
        return Ok(());
    }

    let differing_line = committed
        .lines()
        .zip(regenerated.lines())
        .position(|(left, right)| left != right)
        .map_or_else(
            || committed.lines().count().min(regenerated.lines().count()) + 1,
            |index| index + 1,
        );
    Err(format!(
        "{} differs from regenerated vectors (first differing line {differing_line}); inspect the encoder change and run `just golden-write` if intentional",
        path.display()
    ))
}

fn render() -> Result<String, String> {
    let witness = byte_identity_witness();
    let key_op_witness = key_op_witness();
    let key_op_witness_bytes = witness_schema::canonical_witness_bytes(&key_op_witness);
    let quarantine_claim_witness = quarantine_claim_witness();
    let quarantine_claim_witness_bytes =
        witness_schema::canonical_witness_bytes(&quarantine_claim_witness);
    let state_leaves = state_schema::state_root_leaves(&witness.post_state, &witness.state_sidecar);
    let witness_bytes = witness_schema::canonical_witness_bytes(&witness);
    let deposits = deposit_fixtures();
    let prefix_roots = deposit_prefix_roots(&deposits);

    let mut frontier = empty_deposit_frontier();
    for (index, deposit) in deposits.iter().take(2).enumerate() {
        append_deposit_frontier(&mut frontier, index as u64, deposit)
            .ok_or_else(|| format!("deposit {} does not fit the deposit tree", index + 1))?;
    }

    let high_deposit = high_deposit_fixture();
    let public_inputs = StateTransitionPublicInputs {
        previous_height: 41,
        new_height: 42,
        previous_state_root: [0x10; 32],
        new_state_root: [0x20; 32],
        block_hash: [0x30; 32],
        events_root: [0x40; 32],
        witness_root: [0x50; 32],
        da_commitment: [0x60; 32],
        deposit_root: prefix_roots[2],
        deposit_count: 3,
    };
    let escape_claim_inputs = EscapeClaimPublicInputs {
        state_root: [0x71; 32],
        height: 42,
        account_id: 1001,
        recipient: [0x73; 20],
        amount: 9_876_543_210,
        nullifier: [0x72; 32],
    };

    let raw_key = sec1_key(0x02, 0x11);
    let webauthn_key = sec1_key(0x03, 0x22);
    let account_id = 1001;
    let two_keys_digest = account_keys_digest(
        account_id,
        [
            AccountKeyDigestRecord {
                auth_scheme: 1,
                pubkey_sec1: webauthn_key,
                capability_mask: KeyRecord::FULL_CAPABILITY_MASK,
            },
            AccountKeyDigestRecord {
                auth_scheme: 0,
                pubkey_sec1: raw_key,
                capability_mask: KeyRecord::FULL_CAPABILITY_MASK,
            },
        ],
    );

    let vectors = GoldenVectors {
        _comment: COMMENT,
        schema_version: 4,
        header: HeaderVector {
            fixture: HeaderFixture {
                height: witness.header.height,
                parent_hash: hex_bytes(&witness.header.parent_hash),
                state_root: hex_bytes(&witness.header.state_root),
                events_root: hex_bytes(&witness.header.events_root),
                order_count: witness.header.order_count,
                fill_count: witness.header.fill_count,
                timestamp_ms: witness.header.timestamp_ms,
            },
            hash: hex_bytes(&hash_header(&witness.header)),
        },
        state: StateVector {
            leaf_count: state_leaves.len(),
            framed_sha256: hex_bytes(&digest_state_leaves(&state_leaves)),
            leaves: state_leaves
                .iter()
                .map(|(key, value)| StateLeafVector {
                    key: hex_bytes(key),
                    value: hex_bytes(value),
                })
                .collect(),
        },
        canonical_witness: WitnessVector {
            length: witness_bytes.len(),
            length_prefixed_sha256: hex_bytes(&digest_bytes(&witness_bytes)),
            bytes: hex_bytes(&witness_bytes),
        },
        account_keys: AccountKeysVector {
            account_id,
            raw_p256_key: hex_bytes(&raw_key),
            webauthn_key: hex_bytes(&webauthn_key),
            empty_digest: hex_bytes(&empty_account_keys_digest(account_id)),
            two_keys_digest: hex_bytes(&two_keys_digest),
        },
        key_op_block: KeyOpBlockVector {
            registered_event_leaf: hex_bytes(&event_schema::system_event_leaf_value(
                &key_op_witness.system_events[0],
            )),
            revoked_event_leaf: hex_bytes(&event_schema::system_event_leaf_value(
                &SystemEventWitness::KeyRevoked {
                    account_id,
                    key: KeyRecord {
                        auth_scheme: 1,
                        pubkey_sec1: webauthn_key,
                        capability_mask: KeyRecord::FULL_CAPABILITY_MASK,
                    },
                    authorization: raw_key_op_auth(raw_key, 0x44),
                },
            )),
            register_events_digest_bytes: hex_bytes(&key_event_digest_bytes(
                0x0a,
                KeyRecord {
                    auth_scheme: 1,
                    pubkey_sec1: webauthn_key,
                    capability_mask: KeyRecord::FULL_CAPABILITY_MASK,
                },
                key_op_witness.header.height,
            )),
            revoke_events_digest_bytes: hex_bytes(&key_event_digest_bytes(
                0x0b,
                KeyRecord {
                    auth_scheme: 1,
                    pubkey_sec1: webauthn_key,
                    capability_mask: KeyRecord::FULL_CAPABILITY_MASK,
                },
                key_op_witness.header.height,
            )),
            canonical_witness_length: key_op_witness_bytes.len(),
            canonical_witness_sha256: hex_bytes(&digest_bytes(&key_op_witness_bytes)),
            events_root: hex_bytes(&key_op_witness.header.events_root),
            witness_root: hex_bytes(&witness_root(&key_op_witness)),
        },
        quarantine_claim_block: QuarantineClaimBlockVector {
            quarantined_event_leaf: hex_bytes(&event_schema::system_event_leaf_value(
                &quarantine_claim_witness.system_events[0],
            )),
            claimed_event_leaf: hex_bytes(&event_schema::system_event_leaf_value(
                &quarantine_claim_witness.system_events[1],
            )),
            canonical_witness_length: quarantine_claim_witness_bytes.len(),
            canonical_witness_sha256: hex_bytes(&digest_bytes(&quarantine_claim_witness_bytes)),
            events_root: hex_bytes(&quarantine_claim_witness.header.events_root),
            witness_root: hex_bytes(&witness_root(&quarantine_claim_witness)),
        },
        deposits: DepositVectors {
            chain_id: deposits[0].chain_id,
            vault_address: hex_bytes(&deposits[0].vault_address),
            token_address: hex_bytes(&deposits[0].token_address),
            empty_root: hex_bytes(&empty_deposit_root()),
            entries: deposits
                .iter()
                .zip(prefix_roots.iter())
                .map(|(deposit, root)| DepositVector {
                    deposit_id: deposit.deposit_id,
                    sender: hex_bytes(&deposit.sender),
                    sybil_account_key: hex_bytes(&deposit.sybil_account_key),
                    amount_token_units: deposit.amount_token_units,
                    leaf: hex_bytes(&deposit_leaf(deposit)),
                    tree_leaf: hex_bytes(&deposit_tree_leaf(deposit)),
                    prefix_root: hex_bytes(root),
                })
                .collect(),
            frontier_after_two_level_1: hex_bytes(&frontier[1]),
            high_id_max_amount: HighDepositVector {
                deposit_id: high_deposit.deposit_id,
                sender: hex_bytes(&high_deposit.sender),
                sybil_account_key: hex_bytes(&high_deposit.sybil_account_key),
                amount_token_units: high_deposit.amount_token_units,
                leaf: hex_bytes(&deposit_leaf(&high_deposit)),
                tree_leaf: hex_bytes(&deposit_tree_leaf(&high_deposit)),
            },
        },
        state_transition_public_inputs: PublicInputVector {
            previous_height: public_inputs.previous_height,
            new_height: public_inputs.new_height,
            previous_state_root: hex_bytes(&public_inputs.previous_state_root),
            new_state_root: hex_bytes(&public_inputs.new_state_root),
            block_hash: hex_bytes(&public_inputs.block_hash),
            events_root: hex_bytes(&public_inputs.events_root),
            witness_root: hex_bytes(&public_inputs.witness_root),
            da_commitment: hex_bytes(&public_inputs.da_commitment),
            deposit_root: hex_bytes(&public_inputs.deposit_root),
            deposit_count: public_inputs.deposit_count,
            hash: hex_bytes(&state_transition_public_input_hash(&public_inputs)),
        },
        escape_claim_public_inputs: EscapeClaimPublicInputVector {
            state_root: hex_bytes(&escape_claim_inputs.state_root),
            height: escape_claim_inputs.height,
            account_id: escape_claim_inputs.account_id,
            recipient: hex_bytes(&escape_claim_inputs.recipient),
            amount: escape_claim_inputs.amount,
            nullifier: hex_bytes(&escape_claim_inputs.nullifier),
            hash: hex_bytes(&escape_claim_public_input_hash(&escape_claim_inputs)),
        },
    };

    let mut rendered = serde_json::to_string_pretty(&vectors)
        .map_err(|error| format!("serialize golden vectors: {error}"))?;
    rendered.push('\n');
    Ok(rendered)
}

fn raw_key_op_auth(signer_pubkey: [u8; 33], signature_byte: u8) -> KeyOpAuth {
    KeyOpAuth::RawP256 {
        signer_pubkey,
        signature: [signature_byte; 64],
    }
}

fn key_event_digest_bytes(tag: u8, key: KeyRecord, block_height: u64) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(47);
    bytes.push(tag);
    bytes.push(key.auth_scheme);
    bytes.extend_from_slice(&key.pubkey_sec1);
    bytes.extend_from_slice(&key.capability_mask.to_le_bytes());
    bytes.extend_from_slice(&block_height.to_le_bytes());
    bytes
}

fn escape_claim_public_input_hash(inputs: &EscapeClaimPublicInputs) -> [u8; 32] {
    let encoded = abi_encode_domain_and_words(
        b"sybil/openvm/escape-claim/v1",
        &[
            AbiWord::Bytes32(inputs.state_root),
            AbiWord::Uint(inputs.height),
            AbiWord::Uint(inputs.account_id),
            AbiWord::Address(inputs.recipient),
            AbiWord::Uint(inputs.amount),
            AbiWord::Bytes32(inputs.nullifier),
        ],
    );
    Keccak256::digest(encoded).into()
}

enum AbiWord {
    Uint(u64),
    Address([u8; 20]),
    Bytes32([u8; 32]),
}

fn abi_encode_domain_and_words(domain: &[u8], words: &[AbiWord]) -> Vec<u8> {
    let head_words = 1 + words.len();
    let padded_domain_len = domain.len().div_ceil(32) * 32;
    let mut out = Vec::with_capacity(head_words * 32 + 32 + padded_domain_len);
    out.extend_from_slice(&abi_u64_word((head_words * 32) as u64));
    for word in words {
        match word {
            AbiWord::Uint(value) => out.extend_from_slice(&abi_u64_word(*value)),
            AbiWord::Address(address) => {
                let mut encoded = [0u8; 32];
                encoded[12..].copy_from_slice(address);
                out.extend_from_slice(&encoded);
            }
            AbiWord::Bytes32(bytes) => out.extend_from_slice(bytes),
        }
    }
    out.extend_from_slice(&abi_u64_word(domain.len() as u64));
    out.extend_from_slice(domain);
    out.resize(out.len() + padded_domain_len - domain.len(), 0);
    out
}

fn abi_u64_word(value: u64) -> [u8; 32] {
    let mut out = [0u8; 32];
    out[24..].copy_from_slice(&value.to_be_bytes());
    out
}

fn key_op_witness() -> BlockWitness {
    let account_id = 1001;
    let primary = KeyRecord {
        auth_scheme: 0,
        pubkey_sec1: sec1_key(0x02, 0x11),
        capability_mask: KeyRecord::FULL_CAPABILITY_MASK,
    };
    let agent = KeyRecord {
        auth_scheme: 1,
        pubkey_sec1: sec1_key(0x03, 0x22),
        capability_mask: KeyRecord::FULL_CAPABILITY_MASK,
    };
    let pre = AccountSnapshot {
        id: account_id,
        balance: 0,
        total_deposited: 0,
        positions: Vec::new(),
        events_digest: [0u8; 32],
        keys_digest: account_keys_digest(account_id, [primary]),
    };
    let event_bytes = key_event_digest_bytes(0x0a, agent, 42);
    let mut digest = blake3::Hasher::new();
    digest.update(&pre.events_digest);
    digest.update(&event_bytes);
    let post = AccountSnapshot {
        events_digest: *digest.finalize().as_bytes(),
        keys_digest: account_keys_digest(account_id, [primary, agent]),
        ..pre.clone()
    };
    let event = SystemEventWitness::KeyRegistered {
        account_id,
        key: agent,
        authorization: raw_key_op_auth(primary.pubkey_sec1, 0x33),
    };
    let mut witness = BlockWitness {
        header: WitnessBlockHeader {
            height: 42,
            parent_hash: [0x10; 32],
            state_root: [0x20; 32],
            events_root: [0u8; 32],
            order_count: 0,
            fill_count: 0,
            timestamp_ms: 1_700_000_002_000,
        },
        previous_header: Some(WitnessBlockHeader {
            height: 41,
            parent_hash: [0x01; 32],
            state_root: [0x02; 32],
            events_root: [0x03; 32],
            order_count: 0,
            fill_count: 0,
            timestamp_ms: 1_700_000_001_000,
        }),
        orders: Vec::new(),
        rejections: Vec::new(),
        system_events: vec![event],
        deposit_accumulator: Default::default(),
        fills: Vec::new(),
        clearing_prices: HashMap::new(),
        total_welfare: 0,
        minting_cost: 0,
        mm_constraints: Vec::new(),
        market_groups: Vec::new(),
        pre_state: vec![pre],
        post_system_state: vec![post.clone()],
        post_state: vec![post],
        account_keys: vec![(account_id, vec![primary, agent])],
        state_sidecar: Default::default(),
        pre_state_sidecar: Default::default(),
        resolved_markets: Vec::new(),
    };
    witness.header.events_root =
        sybil_zk::compute_events_root(&witness).expect("key-op events root");
    witness
}

fn quarantine_claim_witness() -> BlockWitness {
    let account_id = 1001;
    let key = bridge_account_key(account_id);
    let amount_token_units = 25_000;
    let amount = 25_000_000i64;
    let deposit = DepositLeaf {
        chain_id: 31_337,
        vault_address: [0x11; 20],
        deposit_id: 1,
        token_address: [0x22; 20],
        sender: [0x33; 20],
        sybil_account_key: key,
        amount_token_units,
    };
    let root = deposit_prefix_roots(std::slice::from_ref(&deposit))[0];
    let deposit = L1DepositWitness {
        deposit_id: 1,
        chain_id: deposit.chain_id,
        vault_address: deposit.vault_address,
        token_address: deposit.token_address,
        sender: deposit.sender,
        sybil_account_key: key,
        amount_token_units,
        deposit_root: root,
    };
    let pre = AccountSnapshot {
        id: account_id,
        balance: 0,
        total_deposited: 0,
        positions: vec![],
        events_digest: [0; 32],
        keys_digest: empty_account_keys_digest(account_id),
    };
    let claim_bytes = {
        let mut bytes = vec![0x0c];
        bytes.extend_from_slice(&amount.to_le_bytes());
        bytes.extend_from_slice(&1u64.to_le_bytes());
        bytes
    };
    let mut digest = blake3::Hasher::new();
    digest.update(&pre.events_digest);
    digest.update(&claim_bytes);
    let post = AccountSnapshot {
        balance: amount,
        total_deposited: amount,
        events_digest: *digest.finalize().as_bytes(),
        ..pre.clone()
    };
    let events = vec![
        SystemEventWitness::DepositQuarantined {
            amount,
            deposit_id: 1,
            deposit_root: root,
            sybil_account_key: key,
        },
        SystemEventWitness::QuarantineClaimed {
            account_id,
            amount,
            sybil_account_key: key,
        },
    ];
    let mut state_sidecar = StateSidecarSnapshot::default();
    state_sidecar.bridge.deposit_cursor = 1;
    state_sidecar.bridge.deposit_root = root;
    let mut witness = BlockWitness {
        header: WitnessBlockHeader {
            height: 1,
            parent_hash: [0; 32],
            state_root: [0; 32],
            events_root: [0; 32],
            order_count: 0,
            fill_count: 0,
            timestamp_ms: 1_700_000_002_000,
        },
        previous_header: None,
        orders: vec![],
        rejections: vec![],
        system_events: events,
        deposit_accumulator: DepositAccumulatorWitness {
            pre_frontier: empty_deposit_frontier(),
            pre_count: 0,
            new_deposits: vec![deposit],
        },
        fills: vec![],
        clearing_prices: HashMap::new(),
        total_welfare: 0,
        minting_cost: 0,
        mm_constraints: vec![],
        market_groups: vec![],
        pre_state: vec![pre],
        post_system_state: vec![post.clone()],
        post_state: vec![post],
        account_keys: vec![],
        state_sidecar,
        pre_state_sidecar: StateSidecarSnapshot::default(),
        resolved_markets: vec![],
    };
    witness.header.state_root = sybil_verifier::block::compute_state_root_with_sidecar(
        &witness.post_state,
        &witness.state_sidecar,
    );
    witness.header.events_root = sybil_zk::compute_events_root(&witness).unwrap();
    assert!(sybil_verifier::verify_full(&witness, false).valid);
    witness
}

fn bridge_account_key(account_id: u64) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new();
    hasher.update(b"sybil/bridge/account-key/v1");
    hasher.update(&account_id.to_le_bytes());
    *hasher.finalize().as_bytes()
}

fn hex_bytes(bytes: &[u8]) -> String {
    format!("0x{}", hex::encode(bytes))
}

fn sec1_key(prefix: u8, body: u8) -> [u8; 33] {
    let mut key = [body; 33];
    key[0] = prefix;
    key
}

fn digest_state_leaves(leaves: &[(Vec<u8>, Vec<u8>)]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    for (key, value) in leaves {
        hasher.update((key.len() as u64).to_le_bytes());
        hasher.update(key);
        hasher.update((value.len() as u64).to_le_bytes());
        hasher.update(value);
    }
    hasher.finalize().into()
}

fn digest_bytes(bytes: &[u8]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update((bytes.len() as u64).to_le_bytes());
    hasher.update(bytes);
    hasher.finalize().into()
}

fn deposit_fixtures() -> [DepositLeaf; 3] {
    [
        DepositLeaf {
            chain_id: 31_337,
            vault_address: [0x11; 20],
            deposit_id: 1,
            token_address: [0x22; 20],
            sender: [0x33; 20],
            sybil_account_key: [0x44; 32],
            amount_token_units: 1_000_000,
        },
        DepositLeaf {
            chain_id: 31_337,
            vault_address: [0x11; 20],
            deposit_id: 2,
            token_address: [0x22; 20],
            sender: [0x55; 20],
            sybil_account_key: [0x66; 32],
            amount_token_units: 2_500_000,
        },
        DepositLeaf {
            chain_id: 31_337,
            vault_address: [0x11; 20],
            deposit_id: 3,
            token_address: [0x22; 20],
            sender: [0x77; 20],
            sybil_account_key: [0x88; 32],
            amount_token_units: 42_000_001,
        },
    ]
}

fn high_deposit_fixture() -> DepositLeaf {
    DepositLeaf {
        chain_id: 31_337,
        vault_address: [0x11; 20],
        deposit_id: 0xfedc_ba98_7654_3210,
        token_address: [0x22; 20],
        sender: [0x99; 20],
        sybil_account_key: [0xaa; 32],
        amount_token_units: u64::MAX,
    }
}

fn byte_identity_witness() -> BlockWitness {
    let market_a = MarketId::new(3);
    let market_b = MarketId::new(9);
    let accepted_order = fixture_order(42, market_a, market_b, 610_000_000, Some(77));
    let rejected_order = fixture_order(7, market_b, market_a, 455_000_000, None);

    let previous_header = WitnessBlockHeader {
        height: 10,
        parent_hash: [1u8; 32],
        state_root: [2u8; 32],
        events_root: [3u8; 32],
        order_count: 4,
        fill_count: 2,
        timestamp_ms: 1_700_000_000_000,
    };
    let header = WitnessBlockHeader {
        height: 11,
        parent_hash: [4u8; 32],
        state_root: [5u8; 32],
        events_root: [6u8; 32],
        order_count: 2,
        fill_count: 1,
        timestamp_ms: 1_700_000_001_234,
    };

    let mut clearing_prices = HashMap::new();
    clearing_prices.insert(market_b, vec![Nanos(410_000_000), Nanos(590_000_000)]);
    clearing_prices.insert(market_a, vec![Nanos(610_000_000), Nanos(390_000_000)]);

    BlockWitness {
        header,
        previous_header: Some(previous_header),
        orders: vec![WitnessOrder {
            order: accepted_order.clone(),
            account_id: 1001,
            is_mm: false,
        }],
        rejections: vec![WitnessRejection {
            order: rejected_order,
            account_id: 1002,
            reason: RejectionReason::InsufficientBalance {
                required: 12_345,
                available: 6_789,
            },
        }],
        system_events: vec![SystemEventWitness::OrderCancelled {
            account_id: 1001,
            order_id: 41,
            market_ids: vec![market_b, market_a],
            side: OrderDirection::SellNo,
            remaining_quantity: 321,
        }],
        deposit_accumulator: sybil_verifier::DepositAccumulatorWitness::default(),
        fills: vec![Fill {
            order_id: 42,
            fill_qty: Qty(250),
            fill_price: Nanos(600_000_000),
            account_id: 1001,
        }],
        clearing_prices,
        total_welfare: 12_345,
        minting_cost: -222,
        mm_constraints: vec![MmConstraint::new(MmId::new(12), Nanos(3_000_000_000))
            .with_order(42, MmSide::BuyYes)
            .with_order(7, MmSide::SellNo)],
        market_groups: vec![MarketGroup {
            name: "Weather basket".to_string(),
            markets: vec![market_b, market_a],
        }],
        pre_state: vec![account_snapshot(1002), account_snapshot(1001)],
        post_system_state: vec![account_snapshot(1001), account_snapshot(1002)],
        post_state: vec![account_snapshot(1002), account_snapshot(1001)],
        account_keys: vec![],
        state_sidecar: state_sidecar(accepted_order),
        pre_state_sidecar: Default::default(),
        resolved_markets: vec![market_b, market_a],
    }
}

fn fixture_order(
    id: u64,
    primary: MarketId,
    secondary: MarketId,
    limit_price: u64,
    expires_at_block: Option<u64>,
) -> Order {
    let mut order = Order::new(id);
    order.markets[0] = primary;
    order.markets[1] = secondary;
    order.num_markets = 2;
    order.num_states = 4;
    order.payoffs[0] = 0;
    order.payoffs[1] = -1;
    order.payoffs[2] = 1;
    order.payoffs[3] = 0;
    order.limit_price = Nanos(limit_price);
    order.max_fill = Qty(500);
    order.condition = Some(PriceCondition {
        market: secondary,
        threshold: Nanos(500_000_000),
        direction: ConditionDir::Above,
    });
    order.expires_at_block = expires_at_block;
    order
}

fn account_snapshot(id: u64) -> AccountSnapshot {
    AccountSnapshot {
        id,
        balance: if id == 1001 { 9_000_000 } else { 7_000_000 },
        total_deposited: if id == 1001 { 10_000_000 } else { 8_000_000 },
        positions: vec![
            (MarketId::new(9), 1, 0),
            (MarketId::new(3), 0, 25),
            (MarketId::new(9), 0, -7),
        ],
        events_digest: [id as u8; 32],
        keys_digest: empty_account_keys_digest(id),
    }
}

fn state_sidecar(resting_order: Order) -> StateSidecarSnapshot {
    let proposal = ResolutionProposalSnapshot {
        id: 88,
        market_id: MarketId::new(3),
        payout_nanos: Nanos(700_000_000),
        source: OracleSourceSnapshot::DataFeed(55),
        proposed_at_ms: 1_700_000_000_100,
        reason: Some("feed quorum".to_string()),
    };
    let challenge = ChallengeSnapshot {
        id: 99,
        challenger: 1002,
        proposal_id: 88,
        bond_amount: Nanos(50_000),
        proposed_payout_nanos: Nanos(300_000_000),
        reason: "disputed source".to_string(),
        challenged_at_ms: 1_700_000_000_200,
    };

    StateSidecarSnapshot {
        bridge: BridgeStateSnapshot {
            deposit_cursor: 14,
            deposit_root: [8u8; 32],
            observed_l1_height: 15,
            next_withdrawal_id: 4,
            withdrawals: vec![WithdrawalSnapshot {
                withdrawal_id: 3,
                account_id: 1001,
                recipient: [9u8; 20],
                token: [10u8; 20],
                amount_token_units: 123_000,
                amount_nanos: 456_000,
                expiry_height: 99,
                nullifier: [11u8; 32],
            }],
            quarantine: vec![],
        },
        markets: vec![
            MarketSnapshot {
                market_id: MarketId::new(9),
                name: "Rain in London".to_string(),
                num_outcomes: 2,
                status: MarketStatusSnapshot::Resolved {
                    record: ResolutionRecordSnapshot {
                        market_id: MarketId::new(9),
                        payout_nanos: Nanos(1_000_000_000),
                        resolved_by: OracleSourceSnapshot::Admin,
                        resolved_at_ms: 1_700_000_000_300,
                        proposal: Some(proposal.clone()),
                        challenge: Some(challenge.clone()),
                    },
                },
                metadata_digest: [12u8; 32],
                resolution_template: "admin_immediate".to_string(),
                last_clearing_prices: vec![Nanos(410_000_000), Nanos(590_000_000)],
            },
            MarketSnapshot {
                market_id: MarketId::new(3),
                name: "Wind over 20kt".to_string(),
                num_outcomes: 2,
                status: MarketStatusSnapshot::Challenged {
                    proposal,
                    challenge,
                },
                metadata_digest: [13u8; 32],
                resolution_template: "data_feed".to_string(),
                last_clearing_prices: vec![Nanos(610_000_000), Nanos(390_000_000)],
            },
        ],
        market_groups: vec![MarketGroupSnapshot {
            group_id: 5,
            name: "Weather basket".to_string(),
            markets: vec![MarketId::new(9), MarketId::new(3)],
        }],
        resting_orders: vec![RestingOrderSnapshot {
            order: resting_order,
            account_id: 1001,
            created_at: 8,
            expires_at_block: 77,
            reserved_balance: 123_456,
            reserved_positions: vec![
                (MarketId::new(9), 1, 0),
                (MarketId::new(3), 0, 12),
                (MarketId::new(9), 0, -5),
            ],
        }],
        account_reservations: vec![AccountReservationSnapshot {
            account_id: 1001,
            reserved_balance: 123_456,
            reserved_positions: vec![
                (MarketId::new(9), 1, 0),
                (MarketId::new(3), 0, 12),
                (MarketId::new(9), 0, -5),
            ],
        }],
    }
}
